### ISSUE TITLE
"The key is Error:"

### ISSUE THREAD

**Issue by andrei4b** [AndreaCogliati/CompleteTranscription#7]
Something is wrong with harmony and/or key process. I get this output:

> Convert MIDI into note list
> Fix overlapping notes
> Detect meter
> Detect beats and quantized notes
> Determine note spelling
> Estimate key
> The key is Error:
> The time signature is 3/4
> Creating score
> Traceback (most recent call last):
> 
>   
> 
> File "<ipython-input-3-19f25e0d91b1>", line 1, in <module>
> 
>     runfile('C:/Users/andre/Desktop/AMT with SS/Music-Transcription-with-Semantic-Segmantation/CompleteTranscription/CompleteTranscription.py', wdir='C:/Users/andre/Desktop/AMT with SS/Music-Transcription-with-Semantic-Segmantation/CompleteTranscription')
> 
>   File "C:\Users\andre\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 704, in runfile
>     execfile(filename, namespace)
> 
>   File "C:\Users\andre\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
>     exec(compile(f.read(), filename, 'exec'), namespace)
> 
>   File "C:/Users/andre/Desktop/AMT with SS/Music-Transcription-with-Semantic-Segmantation/CompleteTranscription/CompleteTranscription.py", line 489, in <module>
>     main()
> 
>   File "C:/Users/andre/Desktop/AMT with SS/Music-Transcription-with-Semantic-Segmantation/CompleteTranscription/CompleteTranscription.py", line 481, in main
>     the_score = complete_transcription(midifile)
> 
>   File "C:/Users/andre/Desktop/AMT with SS/Music-Transcription-with-Semantic-Segmantation/CompleteTranscription/CompleteTranscription.py", line 300, in complete_transcription
>     trebleStaff.insert(0, key.Key(str(midi_score.key)))
> 
>   File "C:\Users\andre\Anaconda3\lib\site-packages\music21-5.5.0-py3.6.egg\music21\key.py", line 869, in __init__
>     sharps = pitchToSharps(tonic, mode)
> 
>   File "C:\Users\andre\Anaconda3\lib\site-packages\music21-5.5.0-py3.6.egg\music21\key.py", line 221, in pitchToSharps
>     value = pitch.Pitch(value)
> 
>   File "C:\Users\andre\Anaconda3\lib\site-packages\music21-5.5.0-py3.6.egg\music21\pitch.py", line 1671, in __init__
>     self._setName(name) # set based on string
> 
>   File "C:\Users\andre\Anaconda3\lib\site-packages\music21-5.5.0-py3.6.egg\music21\pitch.py", line 2505, in _setName
>     self.accidental = Accidental(usrStr[1:])
> 
>   File "C:\Users\andre\Anaconda3\lib\site-packages\music21-5.5.0-py3.6.egg\music21\pitch.py", line 842, in __init__
>     self.set(specifier)
> 
>   File "C:\Users\andre\Anaconda3\lib\site-packages\music21-5.5.0-py3.6.egg\music21\pitch.py", line 1110, in set
>     raise AccidentalException('%s is not a supported accidental type' % name)
> 
> AccidentalException: rror: is not a supported accidental type
> 
>

**Comment by 00sapo** [comment]
@AndreaCogliati I worked on this and solved everything. Note that due to a bug in music21, you have to edit the music21 source code or wait for the next release. See https://github.com/cuthbertLab/music21/issues/419

Here is the working repo: https://framagit.org/sapo/CompleteTranscription
Here is the diff between the two repo: https://diffy.org/diff/2ywku1lz6rg2aupgia32qpvi

However, the output I get is of lower quality than that showed in the paper. Maybe the code should still be fixed...
